---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 4

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.0
  - name: debian-7.7
  - name: fedora-20
  - name: freebsd-10.1
  - name: opensuse-13.1
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[ruby::default]
    attributes:
      ruby:
        gems: [xdite]
