---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 4

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: debian-7.7
  - name: centos-7.0
  - name: fedora-20
  - name: freebsd-10.1
  - name: opensuse-13.1

suites:
  - name: default
    run_list:
      - recipe[cruby]
    attributes:
      ruby:
        gems: [xdite]
